version: "2"

stages:
  - init

tasks:
  print-hello-world:
    stage: init
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/amazonlinux:2023.202501200210
    command:
      - echo "Hello World!"