version: '2'
stages:
  - install
  - lint
  - build
  - test
  - audit_build
  - deploy
var:
  SERVICE_NAME: "gram"
  SERVICE_METADATA_FILE: "c2c-service-metadata.json"
  ARTIFACT_NAME: "l-docker-secure-development-production.artifactory.klarna.net/secure-development/gram"
tasks:
  install:
    stage: install
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/node:22.202608311009-builder
    var:
      NODE_ENV: development
    command:
      - npm install
  lint:
    stage: quality
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/node:22.202608311009-builder
    command:
      - npm run lint
  validate_metadata:
    stage: build
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/tools/kep-cli:6.202608311038
    command:
      - kep c2c service metadata validate --file $SERVICE_METADATA_FILE
  build:
    stage: build
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/node:22.202608311009-builder
    command:
      - npm run build
  test:
    stage: test
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/node:22.202608311009-builder
    resources:
      size: extra-large
    var:
      NODE_ENV: test
      NODE_OPTIONS: --max-old-space-size=4096
    docker: true
    command:
      - docker run --rm -d -e POSTGRES_PASSWORD=somethingsecretfortesting -e POSTGRES_USER=gram-test -p 5433:5432 r-docker-docker-hub.artifactory.klarna.net/postgres:12
      - npm test
  audit_build:
    stage: audit_build
    on:
      - push:
          branches:
            - main
            - develop
    image: kepci
    command:
      - "kepci auditbuild trigger --commitSHA=$COMMIT_HASH --token=audit-build --platformURL=https://audit-build.jenkins.tools.klarna.net"
  deploy_staging:
    stage: deploy
    on:
      - push:
          branches:
            - develop
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/tools/kep-cli:6.202608311038
    var:
      PARTITION: eu
      STAGE: staging
    command:
      - |-
        kep c2c service tag create \
          --service-name "$SERVICE_NAME" \
          --tag "$COMMIT_HASH" \
          --file $SERVICE_METADATA_FILE \
          --docker-url "$ARTIFACT_NAME:$COMMIT_HASH" \
          --wait
      - |-
        kep c2c service deployment start \
          --service-name "$SERVICE_NAME" \
          --partition "$PARTITION" \
          --stage "$STAGE" \
          --tag "$COMMIT_HASH" \
           --wait --skip-image-verification
  deploy_production:
    stage: deploy
    on:
      - push:
          branches:
            - main
    image: l-docker-klarna-production.artifactory.klarna.net/klarna/tools/kep-cli:6.202608311038
    var:
      PARTITION: eu
      STAGE: production
    command:
      - |-
        kep c2c service tag create \
          --service-name "$SERVICE_NAME" \
          --tag "$COMMIT_HASH" \
          --file $SERVICE_METADATA_FILE \
          --docker-url "$ARTIFACT_NAME:$COMMIT_HASH" \
          --wait
      - |-
        kep c2c service deployment start \
          --service-name "$SERVICE_NAME" \
          --partition "$PARTITION" \
          --stage "$STAGE" \
          --tag "$COMMIT_HASH" \
          --wait
arch: arm64
